#!/bin/sh

# FIXME: USER FORGOT TO USE srun (detect and report error?):
# [40000] NOTE at socketconnlist.cpp:218 in scanForPreExisting; REASON='found pre-existing socket... will not be restored'
# fd = 3
# device = socket:[1350385918]
# [Sat Apr 10 09:03:13 2021] [unknown] Fatal error in MPI_Init: Other MPI error, error stack:
# MPIR_Init_thread(537):
# MPID_Init(246).......: channel initialization failed
# MPID_Init(647).......:  PMI2 init failed: 1
# bin/mana_launch: line 48: 15391 Aborted
# $dir/dmtcp_launch $options -h $host --no-gzip --join --disable-dl-plugin --with-plugin $PWD/lib/dmtcp/libmana.so "$target"

# FIXME: USER FORGOT TO USE srun and there is no salloc (detect and report error?):
# + bin/dmtcp_launch 10 -i -h cori03 --no-gzip --join --disable-dl-plugin --with-plugin /global/homes/g/gdc0/mana-rohgarg-orig/lib/dmtcp/libmana.so contrib/mpi-proxy-split/test/ping_pong.mana.exe
# *** ERROR:Executable to run w/ DMTCP appears not to be readable,
# ***or no such executable in path.

if [ "x$1" == x ]; then
  echo "USAGE:  $0 [--verbose] [DMTCP_OPTIONS ...] MANA_EXECUTABLE"
  echo "        For DMTCP options, do: $0 --verbose --help"
  echo "  NOTE: MANA_EXECUTABLE must be compiled with libmpidummy.so"
  exit 1
fi

if [ "x$$SLURM_JOB_ID" == x ]; then
  echo "SLURM_JOB_ID env variable not set; No salloc/sbatch jobs running?"
  exit 2
fi

if ls -d ckpt_rank_* 2>/dev/null 1>&2; then
  echo 'Checkpoint files already in current directory:  ls -d ckpt_rank_*'
  echo 'Please move or delete previous checkpoint before running "mana_launch"'
  exit 3
fi

dir=`dirname $0`
host=`hostname`
submissionHost=`grep Host: $HOME/.mana | sed -e 's%Host: %%'|sed -e 's% .*$%%'`

coordinator_found=0
$dir/dmtcp_command -s -h $submissionHost 1>/dev/null && coordinator_found=1
if [ "$coordinator_found" == 0 ]; then
  echo "*** Checking for coordinator:"
  set -x
    # `dirname $0`/dmtcp_command -s -h `hostname`
    $dir/dmtcp_command --status --coord-host $submissionHost
  set +x
  echo "  No coordinator detected.   Try:"
  echo "    $dir/dmtcp_coordinator --mpi --exit-on-last -q --daemon"
  exit 4
fi

options=""
verbose=0
while [ "x$2" != x ]; do
  if [ "$1" == --verbose ]; then
    verbose=1
  else
    options="$options $1"
  fi
  shift
done

if [ "$verbose" == 0 ]; then
  options="$options -q -q"
fi

target="$1"
plugindir="`dirname $0`/.."

if [ "$verbose" == 1 ]; then
  set -x
fi

$dir/dmtcp_launch  $options --coord-host $submissionHost --no-gzip \
	  --join-coordinator --disable-dl-plugin \
	  --with-plugin $plugindir/lib/dmtcp/libmana.so "$target"

# srun -n1 -c1 --cpu-bind=cores bin/dmtcp_launch  -i10 -h `hostname` --no-gzip --join --disable-dl-plugin --with-plugin $PWD/lib/dmtcp/libmana.so contrib/mpi-proxy-split/test/mpi_hello_world.mana.exe

# srun -n1 -c1 --cpu-bind=cores bin/mana_launch  -i10 contrib/mpi-proxy-split/test/mpi_hello_world.mana.exe
