#!/bin/sh

# FIXME: USER FORGOT TO USE srun (detect and report error?):
# [40000] NOTE at socketconnlist.cpp:218 in scanForPreExisting; REASON='found pre-existing socket... will not be restored'
# fd = 3
# device = socket:[1350385918]
# [Sat Apr 10 09:03:13 2021] [unknown] Fatal error in MPI_Init: Other MPI error, error stack:
# MPIR_Init_thread(537):
# MPID_Init(246).......: channel initialization failed
# MPID_Init(647).......:  PMI2 init failed: 1
# bin/mana_launch: line 48: 15391 Aborted
# $dir/dmtcp_launch $options -h $host --no-gzip --join --disable-dl-plugin --with-plugin $PWD/lib/dmtcp/libmana.so "$target"

# FIXME: USER FORGOT TO USE srun and there is no salloc (detect and report error?):
# + bin/dmtcp_launch 10 -i -h cori03 --no-gzip --join --disable-dl-plugin --with-plugin /global/homes/g/gdc0/mana-rohgarg-orig/lib/dmtcp/libmana.so contrib/mpi-proxy-split/test/ping_pong.mana.exe
# *** ERROR:Executable to run w/ DMTCP appears not to be readable,
# ***or no such executable in path.

# FIXME: USER FORGOT TO DO 'salloc' (detect and report error?):
# gdc0@cori11:~/mana-rohgarg-orig> srun -N 2 bin/mana_launch --verbose contrib/mpi-proxy-split/test/ping_pong.mana.exe
# srun: error: No architecture specified, cannot estimate job costs.
# srun: error: Unable to allocate resources: Unspecified error


if [ "x$1" == x ]; then
  echo "USAGE:  $0 [--verbose] [DMTCP_OPTIONS ...] MANA_EXECUTABLE"
  echo "  NOTE: MANA_EXECUTABLE must be compiled with libmpidummy.so"
  exit 1
fi

if grep -q ckpt_rank*; then
  echo 'Checkpoint files already in current directory:  ls -d ckpt_rank*'
  echo 'Please move or delete the previous checkpoint before running "mana_launch"'
  exit 2
fi


dir=`dirname $0`
host=`hostname`
submissionHost=`grep Host: $HOME/.mana | sed -e 's%Host: %%' | sed -e 's% .*$%%'`
echo $submissionHost

coordinator_found=0
$dir/dmtcp_command -s -h $submissionHost 1>/dev/null && coordinator_found=1
if [ "$coordinator_found" == 0 ]; then
  echo "*** Checking for coordinator:"
  set -x
    # `dirname $0`/dmtcp_command -s -h `hostname` 
    $dir/dmtcp_command --status --coord-host $submissionHost
  set +x
  echo "  No coordinator detected.   Try:"
  echo "    $dir/dmtcp_coordinator --mpi --exit-on-last -q --daemon"
  exit 3
fi

options=""
verbose=0
while [ "x$2" != x ]; do
  if [ "$1" == --verbose ]; then
    verbose=1
  else
    options="$options $1"
  fi
  shift
done

if [ "$verbose" == 0 ]; then
  options="$options -q -q"
fi

target="$1"
plugindir="`dirname $0`/.."

# # FIXME: Can we detect if we're running MPI, and then issue a warning
# #   if we don't detect that srun/sbatch was called?
# # Of course, a user can run a single-rank MPI job without srun/salloc.
# # So, this needs to be a warning, and not an error.
# if ldd "$target" | grep -q libmpidummy.so; then
# fi

# FIXME: Should we detect if the MANA job was not linked with libmpidummy.so
#        and point the user toward dmtcp_launch/dmtcp_restart?
#        Since mana_launch includes the MANA plugin, it's not for non-MPI jobs.

if [ "$verbose" == 1 ]; then
  set -x
fi

$dir/dmtcp_launch  $options --coord-host $submissionHost --no-gzip \
	  --join-coordinator --disable-dl-plugin \
	  --with-plugin $plugindir/lib/dmtcp/libmana.so "$target"

# srun -n1 -c1 --cpu-bind=cores bin/dmtcp_launch  -i10 -h `hostname` --no-gzip --join --disable-dl-plugin --with-plugin $PWD/lib/dmtcp/libmana.so contrib/mpi-proxy-split/test/mpi_hello_world.mana.exe

# srun -n1 -c1 --cpu-bind=cores bin/mana_launch  -i10 contrib/mpi-proxy-split/test/mpi_hello_world.mana.exe
