#!/bin/sh

# FIXME: USER FORGOT TO DO 'salloc' (detect and report error?):
# gdc0@cori11:~/mana-rohgarg-orig> srun -N 2 bin/mana_launch --verbose contrib/mpi-proxy-split/test/ping_pong.mana.exe
# srun: error: No architecture specified, cannot estimate job costs.
# srun: error: Unable to allocate resources: Unspecified error


if [ "x$SLURM_JOB_ID" == x ]; then
  echo "USAGE:  $0 [--verbose] [DMTCP_OPTIONS ...]"
  echo "        For DMTCP options, do: $0 --verbose --help"
  exit 1
fi

dir=`dirname $0`
host=`hostname`
submissionHost=`grep Host: $HOME/.mana | sed -e 's%Host: %%'|sed -e 's% .*$%%'`

coordinator_found=0
$dir/dmtcp_command -s -h $submissionHost 1>/dev/null && coordinator_found=1
if [ "$coordinator_found" == 0 ]; then
  echo "*** Checking for coordinator:"
  set -x
    # `dirname $0`/dmtcp_command -s -h `hostname`
    $dir/dmtcp_command --status --coord-host $submissionHost
  set +x
  echo "  No coordinator detected.   Try:"
  echo "    $dir/dmtcp_coordinator --mpi --exit-on-last -q --daemon"
  exit 2
fi

options=""
verbose=0
while [ "x$1" != x ]; do
  if [ "$1" == --verbose ]; then
    verbose=1
  else
    options="$options $1"
  fi
  shift
done

if [ "$verbose" == 1 ]; then
  set -x
fi

if [ x"$options" == x ]; then
  $dir/dmtcp_command -h $submissionHost --list
else
  $dir/dmtcp_command $options
fi
